"""
Premium Dining Table Showcase Scene
Generated by LLM → USD workflow

This script creates a studio-style scene with:
- Wooden dining table (oak table)
- Two chairs
- Basic studio lighting setup
- Camera positioned for product showcase
- Neutral floor and background

To run in Omniverse Kit:
1. Open Kit app (mdayku)
2. Window → Script Editor
3. Paste this script
4. Click Run
"""

from pxr import Usd, UsdGeom, UsdLux, UsdShade, Gf, Sdf

# Create new stage with timestamp to avoid conflicts
import os
import time

timestamp = int(time.time())
scene_path = f"Z:/omniverse_assets/scenes/dining_table_showcase_{timestamp}.usd"

print(f"Creating scene: {scene_path}")
stage = Usd.Stage.CreateNew(scene_path)

# Set up axis and units
UsdGeom.SetStageUpAxis(stage, UsdGeom.Tokens.y)
UsdGeom.SetStageMetersPerUnit(stage, 1.0)

# Create World root
world = UsdGeom.Xform.Define(stage, "/World")

print("Creating dining table showcase scene...")

# ============================================================================
# FLOOR - Neutral matte surface
# ============================================================================
floor = UsdGeom.Mesh.Define(stage, "/World/Floor")
floor.CreatePointsAttr([
    (-5, 0, -5),
    (5, 0, -5),
    (5, 0, 5),
    (-5, 0, 5)
])
floor.CreateFaceVertexCountsAttr([4])
floor.CreateFaceVertexIndicesAttr([0, 1, 2, 3])
floor.CreateExtentAttr([(-5, 0, -5), (5, 0, 5)])

# Floor material - neutral gray
floor_material = UsdShade.Material.Define(stage, "/World/Floor/FloorMaterial")
floor_shader = UsdShade.Shader.Define(stage, "/World/Floor/FloorMaterial/Shader")
floor_shader.CreateIdAttr("UsdPreviewSurface")
floor_shader.CreateInput("diffuseColor", Sdf.ValueTypeNames.Color3f).Set((0.8, 0.8, 0.8))
floor_shader.CreateInput("roughness", Sdf.ValueTypeNames.Float).Set(0.9)
floor_material.CreateSurfaceOutput().ConnectToSource(floor_shader.ConnectableAPI(), "surface")
UsdShade.MaterialBindingAPI(floor).Bind(floor_material)

print("✓ Floor created")

# ============================================================================
# BACKGROUND - Warm gradient (simulated with plane)
# ============================================================================
background = UsdGeom.Mesh.Define(stage, "/World/Background")
background.CreatePointsAttr([
    (-8, 0, -3),
    (8, 0, -3),
    (8, 5, -3),
    (-8, 5, -3)
])
background.CreateFaceVertexCountsAttr([4])
background.CreateFaceVertexIndicesAttr([0, 1, 2, 3])
background.CreateExtentAttr([(-8, 0, -3), (8, 5, -3)])

# Background material - warm beige
bg_material = UsdShade.Material.Define(stage, "/World/Background/BgMaterial")
bg_shader = UsdShade.Shader.Define(stage, "/World/Background/BgMaterial/Shader")
bg_shader.CreateIdAttr("UsdPreviewSurface")
bg_shader.CreateInput("diffuseColor", Sdf.ValueTypeNames.Color3f).Set((0.95, 0.92, 0.85))
bg_shader.CreateInput("roughness", Sdf.ValueTypeNames.Float).Set(1.0)
bg_material.CreateSurfaceOutput().ConnectToSource(bg_shader.ConnectableAPI(), "surface")
UsdShade.MaterialBindingAPI(background).Bind(bg_material)

print("✓ Background created")

# ============================================================================
# TABLE - Oak dining table (large)
# ============================================================================
# Reference the oak table from Furniture_Misc pack
table_ref = stage.DefinePrim("/World/DiningTable", "Xform")
table_ref.GetReferences().AddReference(
    "Z:/omniverse_assets/packs/Furniture_Misc/Assets/simready_content/common_assets/props/oaktablelarge/oaktablelarge.usd"
)

# Position table at origin, slightly elevated
table_xform = UsdGeom.Xformable(table_ref)
# Clear any existing transform ops to avoid conflicts
table_xform.ClearXformOpOrder()
table_xform.AddTranslateOp(UsdGeom.XformOp.PrecisionDouble).Set((0, 0.75, 0))
table_xform.AddScaleOp(UsdGeom.XformOp.PrecisionFloat).Set((1.0, 1.0, 1.0))

print("✓ Dining table loaded")

# Try to ensure materials load from the referenced asset
table_ref.SetInstanceable(False)  # Make sure we can see inside the reference

# ============================================================================
# CHAIRS - Two chairs positioned at table
# ============================================================================
# Chair 1 - Sappington chair (modern wooden chair)
chair1_ref = stage.DefinePrim("/World/Chair1", "Xform")
chair1_ref.GetReferences().AddReference(
    "Z:/omniverse_assets/packs/Furniture_Misc/Assets/simready_content/common_assets/props/sappington_chair/sappington_chair.usd"
)
chair1_xform = UsdGeom.Xformable(chair1_ref)
chair1_xform.ClearXformOpOrder()
chair1_xform.AddTranslateOp(UsdGeom.XformOp.PrecisionDouble).Set((-0.8, 0, 0.6))
chair1_xform.AddRotateXYZOp(UsdGeom.XformOp.PrecisionFloat).Set((0, 15, 0))  # Slight angle
chair1_xform.AddScaleOp(UsdGeom.XformOp.PrecisionFloat).Set((1.0, 1.0, 1.0))

print("✓ Chair 1 positioned")
chair1_ref.SetInstanceable(False)

# Chair 2 - Second chair on opposite side
chair2_ref = stage.DefinePrim("/World/Chair2", "Xform")
chair2_ref.GetReferences().AddReference(
    "Z:/omniverse_assets/packs/Furniture_Misc/Assets/simready_content/common_assets/props/sappington_chair/sappington_chair.usd"
)
chair2_xform = UsdGeom.Xformable(chair2_ref)
chair2_xform.ClearXformOpOrder()
chair2_xform.AddTranslateOp(UsdGeom.XformOp.PrecisionDouble).Set((0.8, 0, -0.6))
chair2_xform.AddRotateXYZOp(UsdGeom.XformOp.PrecisionFloat).Set((0, -165, 0))  # Facing table
chair2_xform.AddScaleOp(UsdGeom.XformOp.PrecisionFloat).Set((1.0, 1.0, 1.0))

print("✓ Chair 2 positioned")
chair2_ref.SetInstanceable(False)

# ============================================================================
# LIGHTING SETUP - Studio-style lighting
# ============================================================================

# Key Light - Soft natural light from right side (as requested)
key_light = UsdLux.RectLight.Define(stage, "/World/Lights/KeyLight")
key_light.CreateIntensityAttr(5000)  # MUCH brighter
key_light.CreateWidthAttr(3.0)
key_light.CreateHeightAttr(3.0)
key_light.CreateColorAttr((1.0, 0.98, 0.95))  # Warm white
key_light_xform = UsdGeom.Xformable(key_light)
key_light_xform.AddTranslateOp(UsdGeom.XformOp.PrecisionDouble).Set((3, 2.5, 1))
key_light_xform.AddRotateXYZOp(UsdGeom.XformOp.PrecisionFloat).Set((0, -45, 0))

print("✓ Key light (natural from right)")

# Fill Light - Subtle overhead fill
fill_light = UsdLux.RectLight.Define(stage, "/World/Lights/FillLight")
fill_light.CreateIntensityAttr(2000)  # Brighter
fill_light.CreateWidthAttr(4.0)
fill_light.CreateHeightAttr(4.0)
fill_light.CreateColorAttr((1.0, 1.0, 1.0))  # Neutral white
fill_light_xform = UsdGeom.Xformable(fill_light)
fill_light_xform.AddTranslateOp(UsdGeom.XformOp.PrecisionDouble).Set((0, 4, 0))
fill_light_xform.AddRotateXYZOp(UsdGeom.XformOp.PrecisionFloat).Set((90, 0, 0))

print("✓ Fill light (overhead)")

# Rim Light - Subtle back light for depth
rim_light = UsdLux.SphereLight.Define(stage, "/World/Lights/RimLight")
rim_light.CreateIntensityAttr(1500)  # Brighter
rim_light.CreateRadiusAttr(0.5)
rim_light.CreateColorAttr((1.0, 0.95, 0.9))  # Slightly warm
rim_light_xform = UsdGeom.Xformable(rim_light)
rim_light_xform.AddTranslateOp(UsdGeom.XformOp.PrecisionDouble).Set((-2, 2, -2))

print("✓ Rim light (back)")

# Ambient/Environment light
ambient_light = UsdLux.DomeLight.Define(stage, "/World/Lights/DomeLight")
ambient_light.CreateIntensityAttr(2000)  # Much brighter ambient
ambient_light.CreateColorAttr((0.9, 0.92, 0.95))  # Cool ambient

print("✓ Dome light (ambient)")

# ============================================================================
# CAMERA SETUP - Product showcase angle
# ============================================================================
camera = UsdGeom.Camera.Define(stage, "/World/Camera")

# Camera positioned for 3/4 view of table
camera_xform = UsdGeom.Xformable(camera)
camera_xform.AddTranslateOp(UsdGeom.XformOp.PrecisionDouble).Set((2.5, 1.8, 2.5))
camera_xform.AddRotateXYZOp(UsdGeom.XformOp.PrecisionFloat).Set((-20, 45, 0))

# Camera settings for cinematic look
camera.CreateFocalLengthAttr(50)  # Standard lens
camera.CreateFocusDistanceAttr(3.5)
camera.CreateFStopAttr(2.8)  # Shallow depth of field

print("✓ Camera positioned")

# ============================================================================
# ANIMATION SETUP (commented out - enable for animated camera)
# ============================================================================
"""
# To add camera animation later:

# Set time range for animation (e.g., 240 frames at 24fps = 10 seconds)
stage.SetStartTimeCode(0)
stage.SetEndTimeCode(240)

# Example: 360° orbit animation
import math

camera_translate = camera.GetPrim().GetAttribute("xformOp:translate")
camera_rotate = camera.GetPrim().GetAttribute("xformOp:rotateXYZ")

radius = 3.5
height = 1.8

for frame in range(0, 241, 10):  # Keyframe every 10 frames
    angle = (frame / 240.0) * 360.0  # Full rotation
    angle_rad = math.radians(angle)
    
    x = radius * math.cos(angle_rad)
    z = radius * math.sin(angle_rad)
    
    camera_translate.Set((x, height, z), frame)
    camera_rotate.Set((-20, angle - 45, 0), frame)

print("✓ Camera animation added (360° orbit)")

# Example: Slow zoom in
# for frame in range(0, 241):
#     distance = 3.5 - (frame / 240.0) * 1.5  # Zoom from 3.5 to 2.0
#     camera.GetPrim().GetAttribute("xformOp:translate").Set((2.5, 1.8, distance), frame)

# Example: Pan left to right
# for frame in range(0, 241):
#     x_pos = -2.0 + (frame / 240.0) * 4.0  # Pan from -2 to +2
#     camera.GetPrim().GetAttribute("xformOp:translate").Set((x_pos, 1.8, 2.5), frame)
"""

# ============================================================================
# SAVE STAGE
# ============================================================================
stage.GetRootLayer().Save()

print("\n" + "="*60)
print("✅ Scene created successfully!")
print("="*60)
print(f"Scene saved to: {scene_path}")
print("\nNext steps:")
print("1. The scene should now be visible in the viewport")
print("2. If objects appear flat/pink:")
print("   - Check viewport render mode (should be 'Lit' or 'RTX')")
print("   - Try Window → Render Settings → enable materials")
print("3. Use Movie Capture (Window → Movie Capture) to render")
print("4. To add camera animation:")
print("   - Uncomment the animation section in this script")
print("   - Re-run the script")
print("   - Set timeline to 240 frames")
print("   - Render as sequence")
print("\nTip: Press 'F' to frame the scene in viewport")
print("="*60)

